// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var colorClasses, emailIsValid, setupFullPageMediumUp, setupFullPageSmall;
    window.addEventListener('orientationchange', function() {
      return location.reload(false);
    });
    $('#email-modal').on('click', function(e) {
      return $(this).fadeOut();
    });
    $('.join-beta').on('click', function(e) {
      e.preventDefault();
      return $('#email-modal').fadeIn();
    });
    $('input').on('click', function(e) {
      return e.stopImmediatePropagation();
    });
    $('button').on('click', function(e) {
      return e.stopImmediatePropagation();
    });
    emailIsValid = function(email) {
      var emailReg;
      emailReg = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
      return emailReg.test(email);
    };
    setupFullPageSmall = function() {
      $('#fullPageSmall').fullpage({
        sectionSelector: '.sectionSmall',
        loopHorizontal: false,
        controlArrows: true,
        slidesNavigation: false,
        paddingTop: '80px'
      });
      return $.fn.fullpage.setAllowScrolling(true, 'left, right');
    };
    setupFullPageMediumUp = function() {
      return $('#fullpage').fullpage({
        navigation: true,
        fitToSectionDelay: 9999999,
        paddingTop: '50px',
        fixedElements: '.phone',
        onLeave: function(index, nextIndex, direction) {
          var colorClass, _i, _len;
          player_Plan.stop();
          player_Adapt.stop();
          player_Inbox.stop();
          if (index === 1) {
            $('.one .end').fadeOut(200);
            $('.two .end').fadeOut(0);
          } else if (index === 2) {
            $('.two .end').fadeOut(200);
            $('.three .end').fadeOut(0);
          } else if (index === 3) {
            $('.three .end').fadeOut(200);
            $('.four .end').fadeOut(0);
          } else if (index === 4) {
            $('.four .end').fadeOut(200);
            $('.five .end').fadeOut(0);
          } else if (index === 5) {
            $('.five .end').fadeOut(200);
            $('.six .end').fadeOut(0);
          } else if (index === 6) {
            $('.six .end').fadeOut(200);
            $('.fix .end').fadeOut(0);
          }
          for (_i = 0, _len = colorClasses.length; _i < _len; _i++) {
            colorClass = colorClasses[_i];
            $('.section').removeClass(colorClass);
          }
          $('#background').removeClass();
          $('body').removeClass();
          $('#screen').removeClass();
          $('#phone2').removeClass();
          $('#phone3').removeClass();
          $('.down-arrow').removeClass('hide');
          if (nextIndex === 1) {
            $('.one .end').delay(400).fadeIn();
            $('body').addClass('color-one');
            $('#background').addClass('one');
            return $('#screen').addClass('one');
          } else if (nextIndex === 2) {
            $('.two .end').delay(400).fadeIn();
            $('body').addClass('color-two');
            $('#background').addClass('two');
            $('#screen').addClass('two');
            player_Plan.setCurrentFrameNumber(0);
            return player_Plan.play();
          } else if (nextIndex === 3) {
            $('.three .end').delay(400).fadeIn();
            $('body').addClass('color-three');
            $('#background').addClass('three');
            $('#screen').addClass('three');
            player_Adapt.setCurrentFrameNumber(0);
            return player_Adapt.play();
          } else if (nextIndex === 4) {
            $('.four .end').delay(400).fadeIn();
            $('body').addClass('color-four');
            $('#background').addClass('four');
            $('#screen').addClass('four');
            player_Inbox.setCurrentFrameNumber(0);
            return player_Inbox.play();
          } else if (nextIndex === 5) {
            $('.five .end').delay(400).fadeIn();
            $('body').addClass('color-five');
            $('#background').addClass('five');
            $('#screen').addClass('five');
            $('#phone2').addClass('five');
            return $('#phone3').addClass('five');
          } else if (nextIndex === 6) {
            $('.six .end').delay(400).fadeIn();
            $('body').addClass('color-six');
            $('#background').addClass('six');
            $('#screen').addClass('six');
            $('#phone2').addClass('six');
            $('#phone3').addClass('six');
            return $('.down-arrow').addClass('hide');
          }
        }
      });
    };
    $('.email-form').submit(function(e) {
      var action, email, errorField, form, formData, successField;
      e.preventDefault();
      form = $(this);
      action = form.attr('action');
      email = $.trim(form.find('input[name=email]')[0].value);
      successField = $(form.find('.form-message'));
      errorField = $(form.find('.form-error'));
      successField.html('').fadeOut(0);
      errorField.html('').fadeOut(0);
      if (emailIsValid(email)) {
        formData = {
          'email': email
        };
        return $.ajax({
          type: 'POST',
          url: action,
          data: formData,
          dataType: 'json',
          encode: true
        }).fail(function(data) {
          return successField.html('Thank you. You will receive an email soon.').fadeIn();
        });
      } else {
        return errorField.html('Please check your email again. Thanks.').fadeIn();
      }
    });
    colorClasses = ['color-one', 'color-two', 'color-three', 'color-four', 'color-five', 'color-six'];
    $('body').addClass('color-one');
    $('#background').addClass('one');
    $('#screen').addClass('one');
    $('#phone2').addClass('one');
    $('#phone3').addClass('one');
    mediaCheck({
      media: '(max-width: 40em)',
      entry: function() {
        return setupFullPageSmall();
      },
      exit: function() {
        return console.log('');
      }
    });
    return mediaCheck({
      media: '(min-width: 40.063em)',
      entry: function() {
        return setupFullPageMediumUp();
      },
      exit: function() {
        return console.log('');
      }
    });
  });

}).call(this);
