// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var colorClass, colorClasses, _i, _len;
    colorClasses = ['color-one', 'color-two', 'color-three', 'color-four', 'color-five', 'color-six'];
    for (_i = 0, _len = colorClasses.length; _i < _len; _i++) {
      colorClass = colorClasses[_i];
      $('.section').removeClass(colorClass);
      $('.hider').removeClass(colorClass);
    }
    $('.section').addClass('color-one');
    $('.hider').addClass('color-one');
    $('#background').addClass('one');
    return $('#fullpage').fullpage({
      onLeave: function(index, nextIndex, direction) {
        var _j, _len1;
        if (index === 1) {
          $('.one .end').fadeOut(200);
          $('.two .end').fadeOut(0);
        } else if (index === 2) {
          $('.two .end').fadeOut(200);
          $('.three .end').fadeOut(0);
        } else if (index === 3) {
          $('.three .end').fadeOut(200);
          $('.four .end').fadeOut(0);
        } else if (index === 4) {
          $('.four .end').fadeOut(200);
          $('.five .end').fadeOut(0);
        } else if (index === 5) {
          $('.five .end').fadeOut(200);
          $('.six .end').fadeOut(0);
        } else if (index === 6) {
          $('.six .end').fadeOut(200);
          $('.fix .end').fadeOut(0);
        }
        for (_j = 0, _len1 = colorClasses.length; _j < _len1; _j++) {
          colorClass = colorClasses[_j];
          $('.section').removeClass(colorClass);
          $('.hider').removeClass(colorClass);
        }
        $('#background').removeClass();
        if (nextIndex === 1) {
          $('.one .end').delay(400).fadeIn();
          $('.section').addClass('color-one');
          $('.hider').addClass('color-one');
          return $('#background').addClass('one');
        } else if (nextIndex === 2) {
          $('.two .end').delay(400).fadeIn();
          $('.section').addClass('color-two');
          $('.hider').addClass('color-two');
          return $('#background').addClass('two');
        } else if (nextIndex === 3) {
          $('.three .end').delay(400).fadeIn();
          $('.section').addClass('color-three');
          $('.hider').addClass('color-three');
          return $('#background').addClass('three');
        } else if (nextIndex === 4) {
          $('.four .end').delay(400).fadeIn();
          $('.section').addClass('color-four');
          $('.hider').addClass('color-four');
          return $('#background').addClass('four');
        } else if (nextIndex === 5) {
          $('.five .end').delay(400).fadeIn();
          $('.section').addClass('color-five');
          $('.hider').addClass('color-five');
          return $('#background').addClass('five');
        } else if (nextIndex === 6) {
          $('.six .end').delay(400).fadeIn();
          $('.section').addClass('color-six');
          $('.hider').addClass('color-six');
          return $('#background').addClass('six');
        }
      }
    });
  });

}).call(this);
